global:
  scrape_interval: 15s  # Ajusta el intervalo de scrapeo
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Apunta al mismo Prometheus

  - job_name: 'pushgateway'
    honor_labels: true
    metrics_path: /metrics
    static_configs:
      - targets: 
        - pushgateway:9091

  - job_name: 'selenium_grid_exporter'
    honor_labels: true
    metrics_path: /metrics
    static_configs:
      - targets: 
        - seleniumgridexporter:8080